[package]
name = "storage"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
async-trait.workspace = true
tokio.workspace = true
rustix.workspace = true
camino.workspace = true
pin-project.workspace = true
xattr.workspace = true

[dev-dependencies]
tempfile.workspace = true
